### ISSUE TITLE
Reliability cron stopped working

### ISSUE THREAD

**Issue by MoLow** [nodejs/reliability#324]
![image](https://user-images.githubusercontent.com/8221854/179405842-b8e05175-4460-45b5-9dd2-3b045dc8f790.png)
https://github.com/nodejs/reliability/actions

**Comment by MoLow** [comment]
cc @nodejs/actions

**Comment by tniessen** [comment]
I clicked the button to enable it.

![screenshot showing the message "Workflow enabled successfully"](https://user-images.githubusercontent.com/3109072/179528998-cb311b31-cb42-4f18-9274-9b76b39d7f2a.png)
